-- MySQL Script generated by MySQL Workbench
-- Thu Jun 20 10:26:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema educaEventosDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema educaEventosDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `educaEventosDB` DEFAULT CHARACTER SET utf8 ;
USE `educaEventosDB` ;

-- -----------------------------------------------------
-- Table `educaEventosDB`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educaEventosDB`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educaEventosDB`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educaEventosDB`.`evento` (
  `idevento` INT NOT NULL AUTO_INCREMENT,
  `dataFinal` DATETIME NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `inicioEvento` DATETIME NOT NULL,
  `fimEvento` DATETIME NOT NULL,
  `dataInicial` DATETIME NOT NULL,
  PRIMARY KEY (`idevento`),
  UNIQUE INDEX `idevento_UNIQUE` (`idevento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educaEventosDB`.`artigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educaEventosDB`.`artigo` (
  `idartigo` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `texto` VARCHAR(240) NOT NULL,
  `aprovado` INT NULL,
  `evento_idevento` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `parecer` VARCHAR(45) NULL,
  PRIMARY KEY (`idartigo`),
  UNIQUE INDEX `idartigo_UNIQUE` (`idartigo` ASC),
  INDEX `fk_artigo_evento1_idx` (`evento_idevento` ASC),
  INDEX `fk_artigo_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_artigo_evento1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `educaEventosDB`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artigo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `educaEventosDB`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educaEventosDB`.`notaArtigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educaEventosDB`.`notaArtigo` (
  `nota` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `artigo_idartigo` INT NOT NULL,
  `comentario` VARCHAR(45) NOT NULL,
  INDEX `fk_notaArtigo_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_notaArtigo_artigo1_idx` (`artigo_idartigo` ASC),
  PRIMARY KEY (`usuario_idusuario`, `artigo_idartigo`),
  CONSTRAINT `fk_notaArtigo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `educaEventosDB`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notaArtigo_artigo1`
    FOREIGN KEY (`artigo_idartigo`)
    REFERENCES `educaEventosDB`.`artigo` (`idartigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educaEventosDB`.`eventoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educaEventosDB`.`eventoUsuario` (
  `usuario_idusuario` INT NOT NULL,
  `evento_idevento` INT NOT NULL,
  `tipo` ENUM('AVALIADOR', 'COORDENADOR') NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `evento_idevento`),
  INDEX `fk_usuario_has_evento_evento1_idx` (`evento_idevento` ASC),
  INDEX `fk_usuario_has_evento_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_usuario_has_evento_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `educaEventosDB`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_evento_evento1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `educaEventosDB`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
